import currentSchemaCatalogJson from "./app-server-0.154.0-alpha.6.2.schemas.generated.json" with { type: "json" };
import retainedSchemaCatalogJson from "./app-server-0.153.4.schemas.generated.json" with { type: "json" };
import approvedComponentsJson from "./approved-components.json" with { type: "json" };
import compiledSchemaBindingsJson from "./compiled-schema-bindings.json" with { type: "json" };
import type { GeneratedSchemaCatalog } from "./generated-schema-validator.js";

export interface ApprovedCodexComponent {
  id: string;
  status: string;
  cliVersion: string;
  platformOs: string;
  nodePlatform: string;
  architecture: string;
  historyMode: "legacy" | "paginated";
  executable: { filename: string; sha256: string; bytes?: number };
  codeModeHost: { filename: string; sha256: string; bytes: number };
  schema: { filename: string; sha256: string; aggregateSha256: string };
}

export interface CompiledCodexSchemaBinding {
  componentId: string;
  filename: string;
  sha256: string;
  aggregateSha256: string;
  historyMode: "legacy" | "paginated";
}

export interface ApprovedCodexComponentSet {
  component: ApprovedCodexComponent;
  binding: CompiledCodexSchemaBinding;
  schemaCatalog: GeneratedSchemaCatalog;
}

const schemaCatalogsByFilename: Readonly<
  Record<string, GeneratedSchemaCatalog>
> = Object.freeze({
  "app-server-0.154.0-alpha.6.2.schemas.generated.json":
    currentSchemaCatalogJson as unknown as GeneratedSchemaCatalog,
  "app-server-0.153.4.schemas.generated.json":
    retainedSchemaCatalogJson as unknown as GeneratedSchemaCatalog,
});

export function resolveApprovedCodexComponentSet(
  manifest: {
    selection?: string;
    components?: readonly ApprovedCodexComponent[];
  },
  compiledBindings: readonly CompiledCodexSchemaBinding[],
): ApprovedCodexComponentSet {
  const component = manifest.components?.find(
    (entry) => entry.id === manifest.selection,
  );
  if (!component)
    throw new Error(
      `Approved Codex component selection ${String(manifest.selection)} is missing.`,
    );
  if (!["qualified", "retained-qualified"].includes(component.status))
    throw new Error(
      `Approved Codex component ${component.id} has not passed qualification.`,
    );
  const binding = compiledBindings.find(
    (entry) => entry.componentId === component.id,
  );
  if (!binding)
    throw new Error(
      `Approved Codex component ${component.id} has no compiled schema binding.`,
    );
  if (
    binding.filename !== component.schema.filename ||
    binding.sha256 !== component.schema.sha256 ||
    binding.aggregateSha256 !== component.schema.aggregateSha256 ||
    binding.historyMode !== component.historyMode
  )
    throw new Error(
      `Approved Codex component ${component.id} does not match its compiled schema binding.`,
    );
  const schemaCatalog = schemaCatalogsByFilename[binding.filename];
  if (!schemaCatalog)
    throw new Error(
      `Compiled Codex schema ${binding.filename} is not included in the runtime.`,
    );
  if (!schemaCatalog.generatedBy.includes(component.cliVersion))
    throw new Error(
      `Compiled Codex schema ${binding.filename} was not generated by ${component.cliVersion}.`,
    );
  return { component, binding, schemaCatalog };
}

export const APPROVED_CODEX_COMPONENT_SET = resolveApprovedCodexComponentSet(
  approvedComponentsJson as unknown as {
    selection: string;
    components: ApprovedCodexComponent[];
  },
  compiledSchemaBindingsJson.bindings as CompiledCodexSchemaBinding[],
);
