import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

import currentSchemaCatalogJson from "./app-server-0.154.0-alpha.6.2.schemas.generated.json" with { type: "json" };
import retainedSchemaCatalogJson from "./app-server-0.153.4.schemas.generated.json" with { type: "json" };
import approvedComponentsJson from "./approved-components.json" with { type: "json" };
import compiledSchemaBindingsJson from "./compiled-schema-bindings.json" with { type: "json" };
import type { GeneratedSchemaCatalog } from "./generated-schema-validator.js";

export interface ApprovedCodexComponent {
  id: string;
  status: string;
  cliVersion: string;
  platformOs: string;
  nodePlatform: string;
  architecture: string;
  historyMode: "legacy" | "paginated";
  executable: { filename: string; sha256: string; bytes?: number };
  codeModeHost: { filename: string; sha256: string; bytes: number };
  schema: {
    filename: string;
    sha256: string;
    compiledRuntimeSha256: string;
    aggregateSha256: string;
    generatedTsAggregateSha256: string;
  };
}

export interface CompiledCodexSchemaBinding {
  componentId: string;
  filename: string;
  sha256: string;
  compiledRuntimeSha256: string;
  aggregateSha256: string;
  generatedTsAggregateSha256: string;
  historyMode: "legacy" | "paginated";
}

export interface ApprovedCodexComponentSet {
  component: ApprovedCodexComponent;
  binding: CompiledCodexSchemaBinding;
  schemaCatalog: GeneratedSchemaCatalog;
}

interface RuntimeSchemaCatalog extends GeneratedSchemaCatalog {
  generatedTsAggregateSha256: string;
}

export interface RuntimeSchemaCatalogEvidence {
  catalog: RuntimeSchemaCatalog;
  rawFileSha256: string;
}

function catalogEvidence(
  filename: string,
  catalog: RuntimeSchemaCatalog,
): RuntimeSchemaCatalogEvidence {
  return {
    catalog,
    rawFileSha256: createHash("sha256")
      .update(readFileSync(new URL(filename, import.meta.url)))
      .digest("hex"),
  };
}

const schemaCatalogsByFilename: Readonly<
  Record<string, RuntimeSchemaCatalogEvidence>
> = Object.freeze({
  "app-server-0.154.0-alpha.6.2.schemas.generated.json": catalogEvidence(
    "app-server-0.154.0-alpha.6.2.schemas.generated.json",
    currentSchemaCatalogJson as unknown as RuntimeSchemaCatalog,
  ),
  "app-server-0.153.4.schemas.generated.json": catalogEvidence(
    "app-server-0.153.4.schemas.generated.json",
    retainedSchemaCatalogJson as unknown as RuntimeSchemaCatalog,
  ),
});

export function resolveApprovedCodexComponentSet(
  manifest: {
    selection?: string;
    components?: readonly ApprovedCodexComponent[];
  },
  compiledBindings: readonly CompiledCodexSchemaBinding[],
  runtimeCatalogs: Readonly<
    Record<string, RuntimeSchemaCatalogEvidence>
  > = schemaCatalogsByFilename,
): ApprovedCodexComponentSet {
  const component = manifest.components?.find(
    (entry) => entry.id === manifest.selection,
  );
  if (!component)
    throw new Error(
      `Approved Codex component selection ${String(manifest.selection)} is missing.`,
    );
  if (!["qualified", "retained-qualified"].includes(component.status))
    throw new Error(
      `Approved Codex component ${component.id} has not passed qualification.`,
    );
  const binding = compiledBindings.find(
    (entry) => entry.componentId === component.id,
  );
  if (!binding)
    throw new Error(
      `Approved Codex component ${component.id} has no compiled schema binding.`,
    );
  if (
    binding.filename !== component.schema.filename ||
    binding.sha256 !== component.schema.sha256 ||
    binding.compiledRuntimeSha256 !== component.schema.compiledRuntimeSha256 ||
    binding.aggregateSha256 !== component.schema.aggregateSha256 ||
    binding.generatedTsAggregateSha256 !==
      component.schema.generatedTsAggregateSha256 ||
    binding.historyMode !== component.historyMode
  )
    throw new Error(
      `Approved Codex component ${component.id} does not match its compiled schema binding.`,
    );
  const evidence = runtimeCatalogs[binding.filename];
  if (!evidence)
    throw new Error(
      `Compiled Codex schema ${binding.filename} is not included in the runtime.`,
    );
  if (
    evidence.rawFileSha256 !== binding.sha256 &&
    evidence.rawFileSha256 !== binding.compiledRuntimeSha256
  )
    throw new Error(
      `Compiled Codex schema ${binding.filename} raw-file digest does not match its binding.`,
    );
  if (
    evidence.catalog.generatedTsAggregateSha256 !==
    binding.generatedTsAggregateSha256
  )
    throw new Error(
      `Compiled Codex schema ${binding.filename} generated TypeScript aggregate does not match its binding.`,
    );
  if (!evidence.catalog.generatedBy.includes(component.cliVersion))
    throw new Error(
      `Compiled Codex schema ${binding.filename} was not generated by ${component.cliVersion}.`,
    );
  return { component, binding, schemaCatalog: evidence.catalog };
}

export const APPROVED_CODEX_COMPONENT_SET = resolveApprovedCodexComponentSet(
  approvedComponentsJson as unknown as {
    selection: string;
    components: ApprovedCodexComponent[];
  },
  compiledSchemaBindingsJson.bindings as CompiledCodexSchemaBinding[],
);
